import { BaseModel } from '../../_base/crud';

export class ReportModel  extends BaseModel {
    Reports : number;
    Gender:string;
    AttributeName: string;
    Nationality: string;
    SavedFormID: string;
    Sample: string;
    DateAsses: string;
    collected_by: string;
    Collected_point: string;
    Firstname: string;
    Middlename: string;
    Familyname: string;
    dob: string;
    country: string;
    Ethnicity: string;
    sex_mat: string;
    MaritalStatus: string;
    marriage_con: string;
    Numberofwives: string;
    Numberofchildren: string;
    Healthcardnumber: string;
    healthcentre: string;
    Placeofbirth: string;
    Address: string;
    Suburb: string;
    home: string;
    work: string;
    mobile: string;
    comments: string;
    BodyWeight: string;
    Height: string;
    BodyMass: string;
    Waist: string;
    BloodPressureSystolic: string;
    BloodPressureDiastolic: string;
    clinical_hypertension: string;
    diabetesMellitus: string;
    diabetic: string;
    age: string;
    dyslipidemia: string;
    diabetic_other: string;
    diabetes_com: string;
    diabetes_com_specify: string;
    spec_app_retinopathy: string;
    spec_app_neuropathy: string;
    neuropathy_other: string;
    spec_app_cva: string;
    spec_app_nephropathy: string;
    nephropathy_albuminuria_others: string;
    nephropathy_eGFR_others: string;
    spec_app_cad: string;
    diabetes_comp_other_check: string;
    diabetes_comp_others_text: string;
    diabetes_man_none: string;
    diabetes_man_tabletsonly: string;
    diabetes_man_diettablets: string;
    diabetes_man_diettabletsinsulin: string;
    diabetes_man_dietonly: string;
    diabetes_man_insulinonly: string;
    diabetes_man_dietinsulin: string;
    diabetes_man_unknown: string;
    current_diabetes_man_other: string;
    current_diabetes_man_other_text: string;
    bloodCollectedDate: string;
    recentresult: string;
    glucose_collected_date: string;
    glucose_recentresult: string;
    glucose_tolerance_collected_date: string;
    glucose_tolerance_recent_result: string;
    hba1c: string;
    hba1c_RecentResult: string;
    cholesterol_CollectedDate: string;
    cholesterol_RecentResult: string;
    Triglyceride_CollectedDate: string;
    Triglyceride_RecentResult: string;
    HDL_CollectedDate: string;
    HDL_RecentResult: string;
    LDL_CollectedDate: string;
    LDL_RecentResult: string;
    Microalbumin_CollectedDate: string;
    Microalbumin_RecentResult: string;
    Creatinine_CollectedDate: string;
    Creatinine_RecentResult: string;
    Urea_CollectedDate: string;
    Urea_RecentResult: string;
    VitaminD_CollectedDate: string;
    VitaminD_RecentResult: string;
    eGFR_CollectedDate: string;
    eGFR_RecentResult: string;
    lifestyle_walk: string;
    lifestyle_walk_specify: string;
    lifestyle_exercise: string;
    intensity: string;
    healthy: string;
    SpecifyHealthy: string;
    currentSmoke: string;
    medications_allergies: string;
    medications_allergies_specify: string;
    medication_intolerance: string;
    medication_intolerance_specify: string;
    medication_medication: string;
    medication_medication_specify: string;
    inhibit_ace: string;
    perindop: string;
    captopril: string;
    enalapril: string;
    lisinop: string;
    medications_others: string;
    inhibit_arbs: string;
    losartan: string;
    Valsartan: string;
    anti_dose: string;
    inhibit_beta: string;
    atenolol: string;
    bisopr: string;
    beta_dose: string;
    inhibit_diuret: string;
    indapam: string;
    hydroch: string;
    fruse: string;
    diur_others: string;
    inhibit_channel: string;
    amlodip: string;
    nifedip: string;
    verapamil: string;
    diur_inhibit_others: string;
    others_oh: string;
    methyldop: string;
    otr_dose: string;
    AntiRadio_statinsan: string;
    simvast: string;
    atorvast: string;
    rosuvas: string;
    OtherD: string;
    AntiRadio_Fibrates: string;
    gemfib: string;
    fenofib: string;
    fibrat1: string;
    fibrat2: string;
    AntiRadio_others: string;
    AntiOthers: string;
    anti_hyper_Biguanides: string;
    Metformin: string;
    anti_hyper_sus: string;
    glibenclamide: string;
    glimepir: string;
    glipizide: string;
    gliclazide_mr: string;
    glipizide_dose: string;
    pride_dose: string;
    anti_hyper_other_su: string;
    anti_hyper_thiazolid: string;
    anti_hyper_pioglit: string;
    AntiOther: string;
    anti_hyper_meglitin: string;
    anti_hyper_nateglinide: string;
    anti_hyper_nateglinide_repaglinide: string;
    anti_hyper_glucosid: string;
    acarbose: string;
    anti_hyper_dipeptidyl: string;
    sitaglip: string;
    vildaglip: string;
    saxaglip: string;
    linaglip: string;
    anti_hyper_peptid_others: string;
    pramlintide: string;
    other_inhibit: string;
    anti_hyper_incretinm: string;
    exenatide: string;
    liraglut: string;
    exenatide_dose: string;
    anti_hyper_insulin_lin: string;
    lispro_dose: string;
    aspart_dose: string;
    regular_dose: string;
    nph_dose: string;
    Detemir_Dose: string;
    glargine: string;
    insulin_lin_other_su: string;
    combination: string;
    combination_other_su: string;
    anti_hyper_vitamin: string;
    OtherVit: string;
    anti_hyper_prozac: string;
    OthersPro: string;
    anti_hyper_diazepam: string;
    OthersDia: string;
    chin_specify: string;
    diabetes: string;
    diabetesc: string;
    obesity: string;
    hypertension: string;
    cvd: string;
    dyslipidaemia: string;
    familyothers: string;
    grandfa_maside_no: string;
    grandfa_maside_dec: string;
    grandfa_maside_notaff: string;
    grandfa_maside_aff: string;
    grandfa_maside_notsur: string;
    grandma_maside_no: string;
    grandma_maside_dec: string;
    grandma_maside_notaff: string;
    grandma_maside_aff: string;
    grandma_maside_notsur: string;
    grandfa_faside_no: string;
    grandfa_faside_dec: string;
    grandfa_faside_notaff: string;
    grandfa_faside_aff: string;
    grandfa_faside_notsur: string;
    grandma_faside_no: string;
    grandma_faside_dec: string;
    grandma_faside_notaff: string;
    grandma_faside_aff: string;
    grandma_faside_notsur: string;
    ma_no: string;
    ma_dec: string;
    ma_notaff: string;
    ma_aff: string;
    ma_notsur: string;
    fa_no: string;
    fa_dec: string;
    fa_notaff: string;
    fa_aff: string;
    fa_notsur: string;
    sister_no: string;
    sister_dec: string;
    sister_notaff: string;
    sister_aff: string;
    sister_notsur: string;
    brother_no: string;
    brother_dec: string;
    brother_notaff: string;
    brother_aff: string;
    brother_notsur: string;
    wives_no: string;
    wives_dec: string;
    wives_notaff: string;
    wives_aff: string;
    wives_notsur: string;
    husband_no: string;
    husband_dec: string;
    husband_notaff: string;
    husband_aff: string;
    husband_notsur: string;
    son_no: string;
    son_dec: string;
    son_notaff: string;
    son_aff: string;
    son_notsur: string;
    daughters_no: string;
    daughters_dec: string;
    daughters_notaff: string;
    daughters_aff: string;
    daughters_notsur: string;
    grandsons_no: string;
    grandsons_dec: string;
    grandsons_notaff: string;
    grandsons_aff: string;
    grandsons_notsur: string;
    grand_daughters_no: string;
    grand_daughters_dec: string;
    grand_daughters_notaff: string;
    grand_daughters_aff: string;
    grand_daughters_notsur: string;
    uncles_maside_no: string;
    uncles_maside_dec: string;
    uncles_maside_notaff: string;
    uncles_maside_aff: string;
    uncles_maside_notsur: string;
    aunts_maside_no: string;
    aunts_maside_dec: string;
    aunts_maside_notaff: string;
    aunts_maside_aff: string;
    aunts_maside_notsur: string;
    uncles_faside_no: string;
    uncles_faside_dec: string;
    uncles_faside_notaff: string;
    uncles_faside_aff: string;
    uncles_faside_notsur: string;
    aunts_faside_no: string;
    aunts_faside_dec: string;
    aunts_faside_notaff: string;
    aunts_faside_aff: string;
    aunts_faside_notsur: string;
    cousins_maside_aunt_no: string;
    cousins_maside_aunt_dec: string;
    cousins_maside_aunt_notaff: string;
    cousins_maside_aunt_aff: string;
    cousins_maside_aunt_notsur: string;
    cousins_maside_uncle_no: string;
    cousins_maside_uncle_dec: string;
    cousins_maside_uncle_notaff: string;
    cousins_maside_uncle_aff: string;
    cousins_maside_uncle_notsur: string;
    cousins_faside_aunt_no: string;
    cousins_faside_aunt_dec: string;
    cousins_faside_aunt_notaff: string;
    cousins_faside_aunt_aff: string;
    cousins_faside_aunt_notsur: string;
    cousins_faside_uncle_no: string;
    cousins_faside_uncle_dec: string;
    cousins_faside_uncle_notaff: string;
    cousins_faside_uncle_aff: string;
    cousins_faside_uncle_notsur: string;
    family_pedigree: string;
    stride_length: string;
    stride_velocity: string;
    plantar_pres: string;
    Metatarsal_specify: string;
    Reas_specify: string;
    profilePicture: string;
    medication_traditional_chinese: string;
    anti_hyper_nateglinide_others: string;
    acarbose_others: string;
    dipeptidyl_others: string;
    others: string;
    anti_hyper_incretinm_others_dose: string;
    clear() {

    }
}
export class ReportsColumns
{
    Template_id: number;
    Reports : number;
    Gender:string;
    BeginPeriod:string;
    EndPeriod:string;
    AttributeDisplayName: [];
    Nationality: string;
    Collected_by: string;
    Collected_point: string;
    Diabetes : string;
    Sample_id: string;
    Diabetes_mellitus: string;
    Filter: string;
}
export class VitaminD
{
    MobileNumber: string;
    AppRefNo: string;
    FullName: string;
}
export class ArabGenome
{
    MobileNumber: string;
    AppRefNo: string;
    FullName: string;
}
export class Obesity
{
    MobileNumber: string;
    AppRefNo: string;
    FullName: string;
}
export class Osteoporosis
{
    MobileNumber: string;
    AppRefNo: string;
    FullName: string;
}
export class T1Dforms
{
    MobileNumber: string;
    AppRefNo: string;
    FullName: string;
}
export class NewForm
{
    MobileNumber: string;
    AppRefNo: string;
    FullName: string;
}
export class SubstanceDependance
{
    MobileNumber: string;
    AppRefNo: string;
    FullName: string;
}

